### ISSUE TITLE
npm install in arbitrarily selected folder.

### ISSUE THREAD

**Issue by radziksh** [madskristensen/PackageInstaller#10]
Is it possible to add functionality to install rpm packages in arbitrary selected folder? For example add some checkbox, like: "use selected folder in solution explorer". I make widgets, and each of them isolated, because they use different versions of the same libraries. And each has its own package.json. And in this case I have to use the command line instead of the extension. I hope this feature will be useful not only to me.

**Comment by madskristensen** [comment]
npm doesn't allow for custom install directories. It will always dump the files into the *node_modules* folder. It's very unfortunate.

**Comment by radziksh** [comment]
When I said an arbitrary folder I meant folder with its own "node_modules" and "package.json" in it.

**Comment by madskristensen** [comment]
Ahh, got it. This extension cannot do that. The Task Runner Explorer in VS contains the logic about where to look for package.json files and it doesn't look in project sub folders

**Comment by radziksh** [comment]
Really very unfortunate. Ok then. Thanks for the quick response.
