### ISSUE TITLE
Typings support doesn't seem to work correctly

### ISSUE THREAD

**Issue by juliusl** [madskristensen/PackageInstaller#16]
### Installed product versions
- Visual Studio: Visual Studio 2015 Enterprise Update 2
- This extension: 1.8.81

### Description
Typings option does not install. Also the command Package Installer shows doesn't seem to work if you do it manually.

### Steps to recreate
1. Follow instructions for: https://www.typescriptlang.org/docs/handbook/asp-net-4.html

### Current behavior
The typings folder isn't created at all.

### Expected behavior
The typings folder should be created with the typings installed.

**Comment by juliusl** [comment]
To give more context it looks like in the latest version of typings you need to explicitly state the source for DT packages. Currently the Typings provider just passes in the package name to the command. You'll need to save the source information for the package somehow.. or you could always include the source in the command.. 

Basically,

On this line: https://github.com/madskristensen/PackageInstaller/blob/master/src/Providers/Typings.cs#L66
```
yield return obj["name"].ToString();
```

needs to be: 

```
yield return obj["source"].ToString() + "~" + obj["name"].ToString();
```

I think that may solve the problem.

**Comment by madskristensen** [comment]
Fixed
