### ISSUE TITLE
Typings crashes VS 2015

### ISSUE THREAD

**Issue by benerdin** [madskristensen/PackageInstaller#17]
### Installed product versions
- Visual Studio: Enterprise 2015 v14.0.25431.01 Update 3
- This extension: 2.0.94

### Description
I was going through a [TypeScript](https://www.typescriptlang.org/docs/handbook/asp-net-4.html) tutorial that leveraged the PackageInstaller extension. Every time I select Typings and start typing "es6-shim", Visual Studio crashes and restarts.

I repaired the Visual Studio installation, but it didn't change anything.

### Steps to recreate
http://www.screencast.com/t/5RqPOalb

### Current behavior
It's crashing Visual Studio.

### Expected behavior
Not crashing.

**Comment by benerdin** [comment]
Thanks so much for the quick fix!

**Comment by madskristensen** [comment]
Fixed in version 2.0.99
