### ISSUE TITLE
Visual Studio closes when I add a new "Typing" library

### ISSUE THREAD

**Issue by writeless** [madskristensen/PackageInstaller#18]
### Installed product versions
- Visual studio Enterprise 2015 - v14.0.25431.01 Update 3
- This extension: 2.0.94

### Description
Visual Studio closes when I add a new "Typing" library. This happens only with the latest version 2.0.94. I reinstalled version 1.8.85 and disabled the automatic update, and now it works. The error happens when I am typing the library name.

### Steps to recreate
1. With an open solution, I right-click on the web project;
2. Select the "Quick Install Package ..." option;
3. The window of the extension opens [attached figure];
4. Start typing the library name, eg "jquery", but before completing the name, the visual studio closes.
![jquery](https://cloud.githubusercontent.com/assets/22088985/20896699/c5a6a9ee-bafd-11e6-9fb9-9445d65f720c.JPG)

**Comment by madskristensen** [comment]
Fixed in version 2.0.99
