### ISSUE TITLE
Package Installer not functional on VS 2022

### ISSUE THREAD

**Issue by Jaxelr** [madskristensen/PackageInstaller#34]
### Installed product versions
- Visual Studio: [Visual Studio 2022 Community]
- This extension: [2.1.106]

### Description
Package Installer doesnt seem to be working properly on Visual Studio version of 2022 (Community Edition)

### Steps to recreate
1. Installed extension using the Manage Extensions file menu option
2. Selected Package Installer
3. Restarted Visual Studio

### Current behavior
Currently the following functionalities dont work:

- No menu option to add packages
![image](https://user-images.githubusercontent.com/5913008/146110180-1b66a7c7-0119-40b8-ab10-6e0d8fd05ef8.png)

- The shortcut of Alt+Shit+0 is not working

- The Tools - Options - Web - Package Installer option is showing errorloading the page
![image](https://user-images.githubusercontent.com/5913008/146110291-b0f75b54-07a6-4313-be8c-8167617aa5c4.png)

### Expected behavior
I would expect that the extension behave properly

**Comment by helptiger** [comment]
Doesn't work in
Microsoft Visual Studio Community 2022 (64-Bit) 
Version 17.0.4

**Comment by helptiger** [comment]
> Doesn't work in Microsoft Visual Studio Community 2022 (64-Bit) Version 17.0.4

Error loading UI library for package PackageInstallerPackage. HrLoadNativeUILibrary failed with 0x800a006f.
Error loading UI library for package New Project Dialog. HrLoadNativeUILibrary failed with 0x800a006f.
Error loading UI library for package Windows Forms Remote Designer Hosting Package. HrLoadNativeUILibrary failed with 0x800a006f.
Failed to find CTMENU resource '#1000' in loaded UI library.
Error loading UI library for package Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=17.0.0.0, Culture=neutral. HrLoadNativeUILibrary failed with 0x800a006f.

**Comment by red0fireus** [comment]
Got the same error. I downloaded the code myself and changed the appveyor.yml file from "image: Visual Studio 2019" to "image: Visual Studio 2022" and recompiled it and it fixed the issue for me.

**Comment by wikler** [comment]
Any plan fixing this?
Thanks.

**Comment by astrohart** [comment]
Does not work for me either on 17.8.3

**Comment by astrohart** [comment]
Does not work on 17.9

**Comment by astrohart** [comment]
@madskristensen  heads up.  The **Quick Install Package** context menu item will not display when right clicking on a project in **Solution Explorer**.  Please fix this extension!  Thank you.

**Comment by astrohart** [comment]
@madskristensen I know you're busy :-)  But any progress on this issue?  Let me know if there is anything I can do to assist.  I love the **Package Installer** extension's functionality.  

You don't know how many times the compiler is telling me I need some NuGet package or another!  I am like, "oh crap!"  I love just being able to whale on the `SHIFT+ALT+0` key combo and call up the **Quick Install Package** dialog and just install the beast!
