### ISSUE TITLE
Not Loading in VS22 17.6.4

### ISSUE THREAD

**Issue by CodeChaser** [madskristensen/PackageInstaller#36]
**Describe the bug**
Here is one entry in ActivityLog.xml.  Of course there are others but I would assume they are a domino effect.

<entry>
    <record>2499</record>
    <time>2023/07/04 17:18:53.599</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{F91D6656-DCCF-400F-843D-1FF49242CF4B}</guid>
    <hr>0x800a006f</hr>
    <errorinfo>Could not load file or assembly 'PackageInstaller, Version=2.1.106.0, Culture=neutral, PublicKeyToken=null' or one of its 
       dependencies. An attempt was made to load a program with an incorrect format.</errorinfo>
  </entry>

**Comment by astrohart** [comment]
Me too.  Not seeing the command on VS 2022 17.8.3.
