### ISSUE TITLE
Bower package version numbers not retrieved

### ISSUE THREAD

**Issue by djohnst10** [madskristensen/PackageInstaller#4]
When trying to install a Bower package, there are no version numbers retrieved for any package I've tried.

While debugging the `GetVersion` method in the `Bower` class of the extension I discovered that the line:
```c#
string output = await p.StandardOutput.ReadToEndAsync();
```
returns an empty string.

After setting the `RedirectStandardError` property to true in the `ProcessStartInfo` instance, the `output` variable had the expected output which is then parsed correctly.

I experimented with setting the `StandardErrorEncoding` and/or retrieving the `StandardError` but neither was required in order to get the output of the command.

I've experienced a similar issue with the bower package version intellisense in Visual Studio 2015.

My development machine is running Windows 7.

**Comment by madskristensen** [comment]
I cannot reproduce this issue. It works fine for me. I wonder if it's related to differences between Windows 10 and Windows 7

**Comment by djohnst10** [comment]
It's very possible that this does have something to do with Windows 7. I do not see this problem on my Windows 10 machine at home.

**Comment by madskristensen** [comment]
Ok, this is very strange. Let me change it so it redirects StdErr as you describe since that won't cause other issues with this
