### ISSUE TITLE
Visual Studio Crash / Startup Error

### ISSUE THREAD

**Issue by Huntk23** [madskristensen/PackageInstaller#5]
After updating to 1.5.63 this morning and restarting visual studio I am getting an error at startup.

The 'ResourceManagerToolbarPackage' package did not load correctly.

My ActivityLog.xml has this error:
Could not load file or assembly 'Microsoft.VisualStudio.Azure.ResourceManager.Contracts.1.0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I came here first to report the issue because it happened right after updating this extension alone.

**Comment by madskristensen** [comment]
This is an issue caused by a MEF cache corruption and not by this extension. Check this out for a solution https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd
