### ISSUE TITLE
VS Project Compatibility

### ISSUE THREAD

**Issue by cuibty** [madskristensen/PackageInstaller#6]
vs2015 ASP.NET Web Application (ASP.NET 4.6.1template) MVC

After using Package Installer to install bower "bower_components" folder requires each

In Solution Explorer, select Show All Files.

On the Project menu, select Include in Project.

How to solve?

**Comment by madskristensen** [comment]
This is an issue that should be reported to the Visual Studio Web Team and has nothing to do with this extension. Report it here https://github.com/aspnet/tooling/issues
