### ISSUE TITLE
add selectbox for --save --save-dev params

### ISSUE THREAD

**Issue by radziksh** [madskristensen/PackageInstaller#9]
could you, pls, add selectbox to dynamically select the options (--save and --save-dev) in npm? So if you press Shift+Alt+0 and select npm then appears selectbox with --save and save-dev options. Default options should be from Web -> Package Installer -> nmp arguments. Is it possible?

**Comment by madskristensen** [comment]
The latest CI build is available for testing here http://vsixgallery.com/extension/fdd64809-376e-4542-92ce-808a8df06bcc/

**Comment by radziksh** [comment]
Yes, text box works properly. This is what I needed. Thank you.

**Comment by madskristensen** [comment]
Awesome :+1:
